# Generated by Django 6.0.2 on 2026-02-25 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du signalement')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('category', models.CharField(choices=[('PLASTIC', 'Plastique'), ('GLASS', 'Verre'), ('METAL', 'Métal'), ('BIO', 'Organique'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('location', models.CharField(max_length=255, verbose_name='Localisation (adresse ou GPS)')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/%d/', verbose_name='Photo du déchet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
