# Generated by Django 6.0.2 on 2026-02-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu')], default='PENDING', max_length=20),
        ),
    ]
