# Generated by Django 6.0.2 on 2026-02-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_location_alter_report_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_advice',
            field=models.TextField(blank=True, null=True, verbose_name="Conseil de l'IA"),
        ),
    ]
