# Generated by Django 6.0.2 on 2026-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_ai_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('ENERGY_WASTE', 'Gaspillage énergétique (Lumière/Chauffage)'), ('ELEC_ISSUE', 'Problème électrique ou équipement défectueux'), ('WATER_LEAK', "Fuite d'eau ou robinet défectueux"), ('WATER_WASTE', "Gaspillage d'eau"), ('WASTE_FULL', 'Poubelle/Bac de tri plein ou débordant'), ('DEPOSIT_WILD', 'Dépôt sauvage ou déchet mal trié'), ('CLEANLINESS', 'Problème de propreté/hygiène'), ('GREEN_SPACE', 'Espaces verts (Arbre dégradé, plante assoiffée)'), ('ANIMAL_DANGER', 'Protection de la faune locale'), ('ROOM_MISUSE', 'Salle inutilisée restant ouverte/éclairée'), ('OTHER', 'Autre signalement environnemental')], default='OTHER', max_length=20),
        ),
    ]
